Transportation emissions, 2005 - 2022 using territorial framework
Metropolitan-Council/ghg-cprg pull request #104
Opened 2024-07-09 22:45 UTC by eroten

Data changes
- Vehicle miles traveled
  - MN and WI DOT VMT now extend backwards to the earliest published data (2001 for MN, 2009 for WI).
  - For scaling statewide emissions to the county level using VMT, we need a complete time series from our base year (2005) to current year.  MnDOT VMT for year 2015 is unavailable due to _significant and fundemental_ changes in data structure that make directly comparing data prior and post 2015 inappropriate. However, our interpolation here is based on the county level summary of all VMT and centerline mileage using the midpoint method. The midpoint method takes the average of the existing observations directly before and after the missing observation in the sequence. Essentially, we are drawing a direct line between 2014 and 2016. Our interpolation is also only for a single year.
  - Thus, MnDOT daily, annual VMT and centerline mileage has been interpolated for year 2015 using the midpoint method (`zoo::na.approx()`), after summarizing at the county and year levels. Route system was dropped due to changes in route system classifications from year to year. 
  - `dot_vmt` has new column, `cprg_area`, which indicates if the county is in the CPRG study area. This makes for easier joining later on, particularly because there is a Washington County in both MN and WI, but only the MN county is included in the study area. 
- 

New datasets
- County (cprg_population_timeseries) and state (state_population_timeseries) population data from 2005 to 2022. 

Testing changes
- Tests for dot_vmt updated

Quarto changes
- Ensured all dependencies for `dot_vmt` render correctly after adding additional data.

## Checklist

Please complete this checklist as a courtesy to the PR reviewer.  

Code and styling
* [ ] All of the files/scripts I added are in the right place and named appropriately. See the [README](https://github.com/Metropolitan-Council/ghg-cprg/blob/main/README.md) for details.
* [ ] I have not used `setwd()`
* [ ] I have used `file.path(here::here(), "file_name"))` to source any scripts or read in data
* [ ] I have not added any large datasets, unless absolutely necessary (explain)
* [ ] I have commented my code, particularly in hard to understand areas
* [ ] I have added additional package dependencies as necessary with `renv::install()`
* [ ] I have run `styler::style_dir(".", recursive = TRUE, filetype = c("R", "qmd"))`
* [ ] Plots
  - [ ] If plotly, use `source = "chunk-name"` in `plot_ly()`
  - [ ] Use formatting with `councilR::plotly_layout()`?
* [ ] Chunk formatting
  - [ ] All chunks named
  - [ ] All figure or table chunks have caption
  - [ ] `out.width: "95%"`. If a specific height is needed, use pixels. and/or `out.height: "500px"`

Document editing
* [ ] I have ensured that modified documents knit successfully from [`render_for_publication.R`](https://github.com/Metropolitan-Council/ghg-cprg/blob/main/R/render_for_publication.R)
* [ ] I have fixed any missing citations, cross references, hyperlinks
* [ ] I have reviewed my contributions for typos and misspellings.

GitHub and project management
* [ ] I have identified and assigned at least one Reviewer (Liz, Sam, Laine) to this PR
* [ ] I have assigned myself to this PR
* [ ] I have updated the status in the [GitHub Project](https://github.com/orgs/Metropolitan-Council/projects/8/views/1)

2024-10-17 20:54 UTC, pawilfahrt commented on _transportation/data-raw/epa/Re: Seeking guidance on consistent sccs.pdf
@eroten Windows doesn't like the colon in there - can you rename and push?

2024-10-18 18:00 UTC, pawilfahrt commented on _meta/data-raw/epa_us_ghgi.R
> +    emission_grams = as.numeric(emission_grams) * 1000000 %>%
Doesn't this lead right back to where we started?

2024-10-21 18:11 UTC, pawilfahrt commented on _transportation/data-raw/epa_air_emissions_modeling_activity.R
Seems like this script is unfinished or abandoned?

2024-10-21 18:13 UTC, pawilfahrt commented on _transportation/data-raw/epa_air_emissions_modeling_activity.R
Nevermind - needed to reference script_descriptions

2024-10-22 20:09 UTC, pawilfahrt commented on _transportation/data-raw/epa_onroad_emissions_compile.R
> +    co2 = sum(co2, na.rm =T),
Please review the addition of na.rm in these next three combined files - it seemed advantageous to me to have summed gases even when data was missing

2024-10-22 21:09 UTC, pawilfahrt commented on _transportation/data-raw/epa_source_classification_codes.R
code and created rds file looks good but read_download_table fails due to missing pathing. Additional permission issues when troubleshooting. Might be a PC issue?

2024-10-23 19:59 UTC, pawilfahrt requested changes
Whew! Amazing work Liz. There are some smallish changes with a few comments that should be quick approves or reverts.

The one exception is that directly reading files from urls continues to cause problems on my machine. Since this can be worked around by downloading and then directing to a file folder (less elegant but functional) I think it's okay to proceed and troubleshoot elsewhere at a later date.

2024-10-24 17:26 UTC, eroten commented on _transportation/data-raw/epa_source_classification_codes.R
I just pushed a couple changes that should address this. Can you try re-running?

2024-10-24 17:53 UTC, eroten commented on _meta/data-raw/epa_us_ghgi.R
> +    emission_grams = as.numeric(emission_grams) * 1000000 %>%
Yes. I'm not sure where I was going with this, but it isn't used for anything else right now. Can we leave it as is?

2024-10-24 17:56 UTC, eroten commented on _transportation/data-raw/epa_source_classification_codes.R
Resolved in 929b760a19848a9b1e083e98489659854e73e25c

2024-10-24 18:12 UTC, eroten commented on _transportation/data-raw/epa_onroad_emissions_compile.R
> +    co2 = sum(co2, na.rm =T),
Yes, this was more important when I was prepping the data to be interpolated.

2024-10-24 18:45 UTC, merged